### ISSUE TITLE
Cannot complete node_modules/.bin/lockdown-relock command. RangeError

### ISSUE THREAD

**Issue by alexleone** [mozilla/npm-lockdown#36]
Hello I am using lockdown for the first time. I just installed it using <code> npm install --save lockdown</code>

But I can not successfully create the lockdown json. 

I am running the command 
<code>
$ node_modules/.bin/lockdown-relock
</code>
But I am getting the following output. Any Ideas ?
<code>
module.js:169
  var cacheKey = JSON.stringify({request: request, paths: paths});
                      ^
RangeError: Maximum call stack size exceeded
</code>

**Comment by vladikoff** [comment]
Should be fixed in 0.0.8
Please use the tag here: https://github.com/mozilla/npm-lockdown/releases 

The update is **not** on npm yet
