### ISSUE TITLE
publish 0.0.8 on npm

### ISSUE THREAD

**Issue by vladikoff** [mozilla/npm-lockdown#41]
@zaach @seanmonstar ping 

npm still has version 0.0.6 :smile:

**Comment by seanmonstar** [comment]
published!

**Comment by vladikoff** [comment]
amazing! Thanks @seanmonstar

**Comment by willkg** [comment]
I don't see 0.0.8 on npm. I only see 0.0.8-dev:

```
$ npm view lockdown versions 
[ '0.0.1',
  '0.0.2',
  '0.0.3',
  '0.0.4',
  '0.0.5',
  '0.0.6',
  '0.0.8-dev' ]
```

Is that `-dev` release really `0.0.8`?
